In [1]:
%fs ls /databricks-datasets/online_retail/data-001/

In [2]:
# specify path
path = "/databricks-datasets/online_retail/data-001/data.csv"

# read in file using csv format
df = spark.read.load(path,
                    format='com.databricks.spark.csv', 
                    header='true',
                    inferSchema='true')

# show 20 rows
display(df)

In [3]:
display(
   df 
    .select("Country")
    .distinct()
    .orderBy("Country") 
)

In [4]:
order_totals = df.select(df["InvoiceNo"],(df["UnitPrice"]*df["Quantity"]).alias("Total")).groupBy("InvoiceNo").sum()

display(order_totals)

In [5]:
df.filter(df["InvoiceNo"]==536597).show()

In [6]:
display(
  df
    .select(df["Country"], df["Description"],(df["UnitPrice"]*df["Quantity"]).alias("Total"))
    .groupBy("Country", "Description")
    .sum()
    .filter(df["Country"]=="United Kingdom")
    .sort("sum(Total)", ascending=False)
    .limit(10)
  )